package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = [
        "common.cpp",
    ],
    hdrs = [
        "common.h",
    ],
    copts=[
    ],
    deps=[
        "//:llama",
    ]
)
